### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Ehesh** [shyamexe/Dictionary_app_flutter_using_bloc#72]
Hi, I really like this project and how you implemented it and want to use it for a school project. Although I see you put instructions to have people use the code I feel a bit weird using it without an explicit licence file allowing me to use it, that and my teacher will also call me out if there is no licence on the repo I cited. Could you please add a licence to the proyect?

**Comment by shyamexe** [comment]
@Ehesh  Absolutely, I've added a license to the project now. Feel free to use it for your school project, and good luck with your work! If you need anything else, let me know.

**Comment by Ehesh** [comment]
@shyamexe Thankyou so much. I've been busy at school so I did not have the time to reply. I really appreciate it
